### ISSUE TITLE
Does the order matter?

### ISSUE THREAD

**Issue by weiminhuang-corp** [googleinterns/demo-for-google-identity#18]
For these filters, does the order matter? If so add some comments to indicate that.
https://github.com/googleinterns/demo-for-google-identity/blob/6e06ba92d41513fd5fca2bda29b7b388a11dc93c/src/main/java/com/google/googleidentity/config/OAuth2Module.java#L46-L49

**Comment by mcygoogle** [comment]
OK, I will do it.

**Comment by mcygoogle** [comment]
will do it.
