### ISSUE TITLE
Can this be package private?

### ISSUE THREAD

**Issue by weiminhuang-corp** [googleinterns/demo-for-google-identity#24]
https://github.com/googleinterns/demo-for-google-identity/blob/2753bb4563fd8600a2cbe36fbdb8ee9e6eaa5ebc/src/main/java/com/google/googleidentity/oauth2/request/MultipleRequestHandler.java#L29

**Comment by mcygoogle** [comment]
I need to use it for test and it seems @VisibleForTesting is not workable for a class.
